### ISSUE TITLE
How to sharing data between two app using intent and get result with onActivityResult ?

### ISSUE THREAD

**Issue by codingjeremy** [android/storage#9]
<a href="https://github.com/DILEEP-YADAV"><img src="https://avatars3.githubusercontent.com/u/8583769?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DILEEP-YADAV](https://github.com/DILEEP-YADAV)**
_Monday Sep 25, 2017 at 13:27 GMT_
_Originally opened as https://github.com/googlesamples/android-ContentProviderPaging/issues/1_

----

Hi! Please help ! How to sharing data between two app using intent and get result with onActivityResult ?

**Comment by nic0lette** [comment]
The answer is "it depends", because it varies greatly based on the type of data that's being passed between those apps.

Additionally, it would be much better to ask and have this question answered on [Stack Overflow](https://stackoverflow.com) since other people would be able to better benefit from the answer there.

Because of these points, and since the question is so old (sorry!), I'm going to close this.
